use_frameworks!

platform :ios, '9.0'

target 'DynamicBottomSheet_Example' do
  pod 'DynamicBottomSheet', :path => '../'

  target 'DynamicBottomSheet_Tests' do
    inherit! :search_paths

    
  end
end
